import math

from backend.materials import (
    WALL_MATERIALS,
    ROOF_MATERIALS,
    INSULATION_LEVELS,
    ORIENTATION_FACTORS,
)

from backend.optimizer import calculate_design


# -------------------------------------------------------------------
# Prototype size constraints
# -------------------------------------------------------------------
# These are prototype optimization ranges.
# They are NOT statutory NBC size categories.
#
# Floor area = total building floor area in square metres.
# -------------------------------------------------------------------

SIZE_RANGES = {
    "Residential": {
        "Small": (40, 80),
        "Medium": (80, 150),
        "Large": (150, 250),
    },

    "Educational": {
        "Small": (150, 300),
        "Medium": (300, 600),
        "Large": (600, 1200),
    },

    "Commercial": {
        "Small": (100, 250),
        "Medium": (250, 600),
        "Large": (600, 1200),
    },
}


# -------------------------------------------------------------------
# Prototype height ranges
# -------------------------------------------------------------------

HEIGHT_RANGES = {
    "Residential": (2.8, 3.2),
    "Educational": (3.0, 3.6),
    "Commercial": (3.0, 4.0),
}


# -------------------------------------------------------------------
# Generate candidate floor areas
# -------------------------------------------------------------------

def generate_area_candidates(min_area, max_area):

    if max_area <= min_area:
        return [round(min_area, 2)]

    candidates = [
        min_area,
        min_area + (max_area - min_area) * 0.25,
        min_area + (max_area - min_area) * 0.50,
        min_area + (max_area - min_area) * 0.75,
        max_area,
    ]

    return sorted(
        set(round(area, 2) for area in candidates)
    )


# -------------------------------------------------------------------
# Generate dimensions from area
# -------------------------------------------------------------------

def generate_dimensions(area):
    """
    Generate several length/width combinations.

    The dimensions are rounded for display, but the actual
    optimization uses the resulting dimensions.
    """

    aspect_ratios = [
        1.0,
        1.25,
        1.5,
    ]

    dimensions = []

    for ratio in aspect_ratios:

        length = math.sqrt(area * ratio)
        width = area / length

        # Keep dimensions at practical 0.1 m increments.
        length = round(length, 1)
        width = round(width, 1)

        actual_area = length * width

        # Do not allow rounding to push the building outside
        # the selected size range.
        dimensions.append(
            {
                "length": length,
                "width": width,
                "actual_area": round(actual_area, 2),
            }
        )

    return dimensions


# -------------------------------------------------------------------
# Generate building heights
# -------------------------------------------------------------------

def generate_heights(building_type):

    min_height, max_height = HEIGHT_RANGES[building_type]

    midpoint = (min_height + max_height) / 2

    return [
        round(min_height, 1),
        round(midpoint, 1),
        round(max_height, 1),
    ]


# -------------------------------------------------------------------
# Evaluate one candidate
# -------------------------------------------------------------------

def evaluate_candidate(
    climate,
    building_type,
    size_category,
    length,
    width,
    height,
):
    results = []

    for wall in WALL_MATERIALS:

        for roof in ROOF_MATERIALS:

            for insulation in INSULATION_LEVELS:

                for orientation in ORIENTATION_FACTORS:

                    result = calculate_design(
                        climate=climate,
                        length=length,
                        width=width,
                        height=height,
                        wall=wall,
                        roof=roof,
                        insulation=insulation,
                        orientation=orientation,
                    )

                    # Add the dimensions generated by the AI.
                    result["length"] = length
                    result["width"] = width
                    result["height"] = height

                    result["building_type"] = building_type
                    result["size_category"] = size_category

                    results.append(result)

    return results


# -------------------------------------------------------------------
# Generate and optimize shelter
# -------------------------------------------------------------------

def generate_shelter_design(
    climate,
    building_type,
    size_category,
):

    # ---------------------------------------------------------------
    # Validate building type
    # ---------------------------------------------------------------

    if building_type not in SIZE_RANGES:
        raise ValueError(
            f"Unknown building type: {building_type}"
        )

    # ---------------------------------------------------------------
    # Validate size category
    # ---------------------------------------------------------------

    if size_category not in SIZE_RANGES[building_type]:
        raise ValueError(
            f"Unknown size category '{size_category}' "
            f"for building type '{building_type}'"
        )

    # ---------------------------------------------------------------
    # Selected floor-area range
    # ---------------------------------------------------------------

    min_area, max_area = SIZE_RANGES[
        building_type
    ][size_category]

    area_candidates = generate_area_candidates(
        min_area,
        max_area,
    )

    height_candidates = generate_heights(
        building_type
    )

    all_results = []

    # ---------------------------------------------------------------
    # Search design space
    # ---------------------------------------------------------------

    for area in area_candidates:

        dimensions = generate_dimensions(area)

        for dimension in dimensions:

            length = dimension["length"]
            width = dimension["width"]

            actual_area = dimension["actual_area"]

            # -------------------------------------------------------
            # Make sure rounded dimensions stay inside the selected
            # size category.
            # -------------------------------------------------------

            if actual_area < min_area:
                continue

            if actual_area > max_area:
                continue

            for height in height_candidates:

                candidates = evaluate_candidate(
                    climate=climate,
                    building_type=building_type,
                    size_category=size_category,
                    length=length,
                    width=width,
                    height=height,
                )

                all_results.extend(candidates)

    # ---------------------------------------------------------------
    # Safety check
    # ---------------------------------------------------------------

    if not all_results:
        raise ValueError(
            "Unable to generate shelter designs "
            "within the selected size range."
        )

    # ---------------------------------------------------------------
    # Rank designs
    # ---------------------------------------------------------------
    #
    # Primary objective:
    #     Lower heat loss
    #
    # Secondary objective:
    #     Higher thermal score
    # ---------------------------------------------------------------

    all_results.sort(
        key=lambda result: (
            result["heat_loss_kw"],
            -result["thermal_score"],
        )
    )

    # ---------------------------------------------------------------
    # Best design
    # ---------------------------------------------------------------

    best_design = all_results[0]

    # ---------------------------------------------------------------
    # Top 3 alternatives
    # ---------------------------------------------------------------

    recommendations = []

    for rank, result in enumerate(
        all_results[:3],
        start=1,
    ):

        result["rank"] = rank

        recommendations.append(result)

    # ---------------------------------------------------------------
    # Return result
    # ---------------------------------------------------------------

    return {
        "building_type": building_type,
        "size_category": size_category,

        "area_range": {
            "minimum": min_area,
            "maximum": max_area,
        },

        "best_design": best_design,

        "recommendations": recommendations,
    }